"""Adjusted matches and tournament schema

Revision ID: 822c9d987319
Revises: 2ccf3198f46b
Create Date: 2021-08-31 21:27:26.074077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822c9d987319'
down_revision = '2ccf3198f46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('round', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('winner_match_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'match', ['winner_match_id'], ['match_id'])
    op.drop_column('match', 'match_number')
    op.add_column('tournament', sa.Column('is_seeded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'is_seeded')
    op.add_column('match', sa.Column('match_number', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'winner_match_id')
    op.drop_column('match', 'round')
    # ### end Alembic commands ###
