"""tournament table updates

Revision ID: 9a3eb12a0030
Revises: 
Create Date: 2021-02-14 21:32:29.321691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3eb12a0030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_status',
    sa.Column('match_status_id', sa.Integer(), nullable=False),
    sa.Column('match_status_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('match_status_id')
    )
    op.create_table('tournament_status',
    sa.Column('tournament_status_id', sa.Integer(), nullable=False),
    sa.Column('tournament_status_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('tournament_status_id')
    )
    op.create_table('tournament',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=255), nullable=True),
    sa.Column('tournament_description', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tournament_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_status_id'], ['tournament_status.tournament_status_id'], ),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('participant',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.tournament_id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('participant_a_score', sa.Integer(), nullable=True),
    sa.Column('participant_b_score', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('participant_a_id', sa.Integer(), nullable=True),
    sa.Column('participant_b_id', sa.Integer(), nullable=True),
    sa.Column('match_status_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_status_id'], ['match_status.match_status_id'], ),
    sa.ForeignKeyConstraint(['participant_a_id'], ['participant.participant_id'], ),
    sa.ForeignKeyConstraint(['participant_b_id'], ['participant.participant_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.tournament_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('participant')
    op.drop_table('tournament')
    op.drop_table('tournament_status')
    op.drop_table('match_status')
    # ### end Alembic commands ###
