"""Added winner_id to match

Revision ID: a26258c39d75
Revises: a7e6bc37d69e
Create Date: 2021-10-13 14:41:37.586245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26258c39d75'
down_revision = 'a7e6bc37d69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'participant', ['winner_id'], ['participant_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'winner_id')
    # ### end Alembic commands ###
