"""Added dark mode to user

Revision ID: a7e6bc37d69e
Revises: bd403a22ecc4
Create Date: 2021-09-29 14:21:37.762501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e6bc37d69e'
down_revision = 'bd403a22ecc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dark_mode')
    # ### end Alembic commands ###
