"""Added registration date to user

Revision ID: bd403a22ecc4
Revises: 9c35732d1d52
Create Date: 2021-09-28 15:12:37.870964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd403a22ecc4'
down_revision = '9c35732d1d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'register_date')
    # ### end Alembic commands ###
